# ~/.config/starship.toml
# https://starship.rs/config/#lua
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 10000


[directory]
style = "bg:bright-blue"
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = false

[character]
success_symbol = "■ "
error_symbol = "● "
format = "$symbol"

[git_branch]
style = "bg:#F05032"
format = "[ $symbol$branch(:$remote_branch)]($style)"
always_show_remote = true


[git_status]
style = "bg:#F05032"
format = '([ \[$all_status$ahead_behind\] ]($style))'

[package]
format = " is [$symbol$version]($style)"
disabled = true

[aws]
disabled = true

[conda]
style = "bg:#43B02A"
format = '[ $environment ]($style)'

[container]
disabled = false

[rlang]
disabled = false

[julia]
disabled = false

[ruby]
disabled = false

[os]
disabled = true

[rust]
symbol = "Rust "
style = "bg:#CE422B"
format = '[ $symbol($version) ]($style)'
disabled = false

[dotnet]
style = "bg:#512BD4"
format = '[ $symbol($version) (🎯$tfm) ]($style)'
heuristic = false
disabled = false

[golang]
symbol = "Go "
style = "bg:#00ADD8"
disabled = false

[lua]
symbol = "Lua "
style = "bg:#001A70"
format = "[ $symbol($version) ]($style)"
disabled = false

[line_break]
disabled = false

[time]
format = "🕰️ [$time]($style) "
disabled = false

[cmd_duration]
format = "⏱️ [$duration]($style) "
disabled = false

[shlvl]
disabled = false
format = '[$symbol]($style) / '
repeat = true
symbol = '❯'
repeat_offset = 1

[python]
symbol = "PY "
style = ""
format = '[ ${symbol}](bg:#FFD43B)[ ${pyenv_prefix}(${version}) ](bg:#3776AB)[ (\($virtualenv\)) ](bg:#b7bdf8)'


